#!/bin/bash
## to be call after ./build-apk
set -e
set -o pipefail

cd apk
f="app-release-signed.apk"
ipfs add -w "$f"
mkdir -p surge
cp "$f" surge/
surge surge zeronet-profile-chooser.surge.sh
ipfs add -w "$f"
